### PR TITLE
[ADDED] min/max and operator options to the exports.mathExpr, extended d tests and (english) readme

### PR DESCRIPTION
**Pull request by j-d-carmichael**
If you require tougher math expressions these additional options allow this now: mathOperator mathMin mathMax added with default values to ensure this is a non-breaking change to the existing code base.

### CODE REVIEW

**Comment by lichaozhy** [comment]
There are many design problems in v1.x. They are all my mistakes. I would rather stop maintaining for v1.x. Do you really need me to release a new version? Or we should refactor v3.x? I have a lot of new ideas about that.

But if you really need v1.x to be released, I will accept it. The version will be v1.4.0.

**Comment by j-d-carmichael** [comment]
Currently I have pulled this into my project directly from github but this is not a nice solution for when my current project goes live in a month or so. Therefore if it is not too much trouble to release this to v1 that would be great.

**Comment by lichaozhy** [comment]
As you wish 😋

**Comment by j-d-carmichael** [comment]
:D you absolute star! Thank you!

(looking forward to seeing the release of v3!)

**Comment by kerem3322** [comment]
merhaba site kurcamda yardımcı olurmusun ?

**Pull request merged**
